In [38]:
import numpy as np

In [39]:
#from simple lists
a = [[1, 2, 3, 4], [5, 6, 7, 8]]
np_a = np.array(a)
np_a, type(np_a)

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 numpy.ndarray)

In [40]:
#zeros - fill with zeros
z = np.zeros([3, 3])
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
#ones - fill with ones
o = np.ones([2, 3, 4])
o

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [42]:
#arange - from the range
ar = np.arange(2, 23, 4)
ar

array([ 2,  6, 10, 14, 18, 22])

In [43]:
#eye - identity matrix
e = np.eye(4)
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [44]:
#shape, dtype
o.shape, o.dtype

((2, 3, 4), dtype('float64'))

In [53]:
#lets look at the first and the last element of the array 'arr'
arr = np.empty([2, 3])
print(f'The first element:\n{arr[0]}\nThe last element:\n{arr[-1]}\nThe array:\n{arr}')

The first element:
[6.12906116e-310 6.12906116e-310 0.00000000e+000]
The last element:
[0. 0. 0.]
The array:
[[6.12906116e-310 6.12906116e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [86]:
#lets look at the elements between first and the last columns of the array 'arr1'
arr1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]])
arr1[:, 1:-1]

array([[2, 3, 4],
       [7, 8, 9]])

In [88]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [89]:
#Addition a + b
a + b

array([5, 7, 9])

In [ ]:
#Subtraction
a - b

array([-3, -3, -3])

In [ ]:
#Multiplication
a * b

array([ 4, 10, 18])

In [93]:
#Division
a / b

array([0.25, 0.4 , 0.5 ])

In [ ]:
#Mean of the elements of the array 'a'
a.mean()

np.float64(2.0)

In [ ]:
#Max of the elements of the array 'a'
a.max()

np.int64(3)